version: '3.1'

services:

  api:
    build: ./
    restart: always
    ports:
      - 8085:8080
    environment:
      - POSTGRE_USERNAME=${POSTGRE_USERNAME}
      - POSTGRE_USER_PASSWORD=${POSTGRE_USER_PASSWORD}

  ui:
    build: ./ui/
    ports:
      - 3000:3000
    depends_on:
      - api
    restart: always

