insert into public.currencies (id, code, name) values (1, '	USD', '	US Dollar');
insert into public.currencies (id, code, name) values (2, '	EUR', '	Euro');
insert into public.currencies (id, code, name) values (3, '	UAH', '	Hryvnia');
insert into public.currencies (id, code, name) values (4, '	GBP', '	Pound Sterling');
insert into public.currencies (id, code, name) values (5, '	RUB', '	Russian Ruble');
insert into public.currencies (id, code, name) values (6, '	AFN', '	Afghani');
insert into public.currencies (id, code, name) values (7, '	ALL', '	Lek');
insert into public.currencies (id, code, name) values (8, '	DZD', '	Algerian Dinar');
insert into public.currencies (id, code, name) values (9, '	AOA', '	Kwanza');
insert into public.currencies (id, code, name) values (10, '	XCD', '	East Caribbean Dollar');
insert into public.currencies (id, code, name) values (11, '	ARS', '	Argentine Peso');
insert into public.currencies (id, code, name) values (12, '	AMD', '	Armenian Dram');
insert into public.currencies (id, code, name) values (14, '	AUD', '	Australian Dollar');
insert into public.currencies (id, code, name) values (15, '	AZN', '	Azerbaijan Manat');
insert into public.currencies (id, code, name) values (16, '	BSD', '	Bahamian Dollar');
insert into public.currencies (id, code, name) values (17, '	BHD', '	Bahraini Dinar');
insert into public.currencies (id, code, name) values (18, '	BDT', '	Taka');
insert into public.currencies (id, code, name) values (19, '	BBD', '	Barbados Dollar');
insert into public.currencies (id, code, name) values (20, '	BYN', '	Belarusian Ruble');
insert into public.currencies (id, code, name) values (21, '	BZD', '	Belize Dollar');
insert into public.currencies (id, code, name) values (22, '	XOF', '	CFA Franc BCEAO');
insert into public.currencies (id, code, name) values (23, '	BMD', '	Bermudian Dollar');
insert into public.currencies (id, code, name) values (24, '	INR', '	Indian Rupee');
insert into public.currencies (id, code, name) values (25, '	BTN', '	Ngultrum');
insert into public.currencies (id, code, name) values (26, '	BOB', '	Boliviano');
insert into public.currencies (id, code, name) values (27, '	BOV', '	Mvdol');
insert into public.currencies (id, code, name) values (28, '	BAM', '	Convertible Mark');
insert into public.currencies (id, code, name) values (29, '	BWP', '	Pula');
insert into public.currencies (id, code, name) values (30, '	NOK', '	Norwegian Krone');
insert into public.currencies (id, code, name) values (31, '	BRL', '	Brazilian Real');
insert into public.currencies (id, code, name) values (32, '	BND', '	Brunei Dollar');
insert into public.currencies (id, code, name) values (33, '	BGN', '	Bulgarian Lev');
insert into public.currencies (id, code, name) values (34, '	BIF', '	Burundi Franc');
insert into public.currencies (id, code, name) values (35, '	CVE', '	Cabo Verde Escudo');
insert into public.currencies (id, code, name) values (36, '	KHR', '	Riel');
insert into public.currencies (id, code, name) values (37, '	XAF', '	CFA Franc BEAC');
insert into public.currencies (id, code, name) values (38, '	CAD', '	Canadian Dollar');
insert into public.currencies (id, code, name) values (39, '	KYD', '	Cayman Islands Dollar');
insert into public.currencies (id, code, name) values (40, '	CLP', '	Chilean Peso');
insert into public.currencies (id, code, name) values (41, '	CLF', '	Unidad de Fomento');
insert into public.currencies (id, code, name) values (42, '	CNY', '	Yuan Renminbi');
insert into public.currencies (id, code, name) values (43, '	COP', '	Colombian Peso');
insert into public.currencies (id, code, name) values (44, '	COU', '	Unidad de Valor Real');
insert into public.currencies (id, code, name) values (45, '	KMF', '	Comorian Franc');
insert into public.currencies (id, code, name) values (46, '	CDF', '	Congolese Franc');
insert into public.currencies (id, code, name) values (47, '	NZD', '	New Zealand Dollar');
insert into public.currencies (id, code, name) values (48, '	CRC', '	Costa Rican Colon');
insert into public.currencies (id, code, name) values (49, '	HRK', '	Kuna');
insert into public.currencies (id, code, name) values (50, '	CUP', '	Cuban Peso');
insert into public.currencies (id, code, name) values (51, '	CUC', '	Peso Convertible');
insert into public.currencies (id, code, name) values (52, '	ANG', '	Netherlands Antillean Guilder');
insert into public.currencies (id, code, name) values (53, '	CZK', '	Czech Koruna');
insert into public.currencies (id, code, name) values (54, '	DKK', '	Danish Krone');
insert into public.currencies (id, code, name) values (55, '	DJF', '	Djibouti Franc');
insert into public.currencies (id, code, name) values (56, '	DOP', '	Dominican Peso');
insert into public.currencies (id, code, name) values (57, '	EGP', '	Egyptian Pound');
insert into public.currencies (id, code, name) values (58, '	SVC', '	El Salvador Colon');
insert into public.currencies (id, code, name) values (59, '	ERN', '	Nakfa');
insert into public.currencies (id, code, name) values (60, '	ETB', '	Ethiopian Birr');
insert into public.currencies (id, code, name) values (61, '	FKP', '	Falkland Islands Pound');
insert into public.currencies (id, code, name) values (62, '	FJD', '	Fiji Dollar');
insert into public.currencies (id, code, name) values (63, '	XPF', '	CFP Franc');
insert into public.currencies (id, code, name) values (64, '	GMD', '	Dalasi');
insert into public.currencies (id, code, name) values (65, '	GEL', '	Lari');
insert into public.currencies (id, code, name) values (66, '	GHS', '	Ghana Cedi');
insert into public.currencies (id, code, name) values (67, '	GIP', '	Gibraltar Pound');
insert into public.currencies (id, code, name) values (68, '	GTQ', '	Quetzal');
insert into public.currencies (id, code, name) values (69, '	GNF', '	Guinean Franc');
insert into public.currencies (id, code, name) values (70, '	GYD', '	Guyana Dollar');
insert into public.currencies (id, code, name) values (71, '	HTG', '	Gourde');
insert into public.currencies (id, code, name) values (72, '	HNL', '	Lempira');
insert into public.currencies (id, code, name) values (73, '	HKD', '	Hong Kong Dollar');
insert into public.currencies (id, code, name) values (74, '	HUF', '	Forint');
insert into public.currencies (id, code, name) values (75, '	ISK', '	Iceland Krona');
insert into public.currencies (id, code, name) values (76, '	IDR', '	Rupiah');
insert into public.currencies (id, code, name) values (77, '	XDR', '	SDR (Special Drawing Right)');
insert into public.currencies (id, code, name) values (78, '	IRR', '	Iranian Rial');
insert into public.currencies (id, code, name) values (79, '	IQD', '	Iraqi Dinar');
insert into public.currencies (id, code, name) values (80, '	ILS', '	New Israeli Sheqel');
insert into public.currencies (id, code, name) values (81, '	JMD', '	Jamaican Dollar');
insert into public.currencies (id, code, name) values (82, '	JPY', '	Yen');
insert into public.currencies (id, code, name) values (83, '	JOD', '	Jordanian Dinar');
insert into public.currencies (id, code, name) values (84, '	KZT', '	Tenge');
insert into public.currencies (id, code, name) values (85, '	KES', '	Kenyan Shilling');
insert into public.currencies (id, code, name) values (86, '	KPW', '	North Korean Won');
insert into public.currencies (id, code, name) values (87, '	KRW', '	Won');
insert into public.currencies (id, code, name) values (88, '	KWD', '	Kuwaiti Dinar');
insert into public.currencies (id, code, name) values (89, '	KGS', '	Som');
insert into public.currencies (id, code, name) values (90, '	LAK', '	Lao Kip');
insert into public.currencies (id, code, name) values (91, '	LBP', '	Lebanese Pound');
insert into public.currencies (id, code, name) values (92, '	LSL', '	Loti');
insert into public.currencies (id, code, name) values (93, '	ZAR', '	Rand');
insert into public.currencies (id, code, name) values (94, '	LRD', '	Liberian Dollar');
insert into public.currencies (id, code, name) values (95, '	LYD', '	Libyan Dinar');
insert into public.currencies (id, code, name) values (96, '	CHF', '	Swiss Franc');
insert into public.currencies (id, code, name) values (97, '	MOP', '	Pataca');
insert into public.currencies (id, code, name) values (98, '	MKD', '	Denar');
insert into public.currencies (id, code, name) values (99, '	MGA', '	Malagasy Ariary');
insert into public.currencies (id, code, name) values (100, '	MWK', '	Malawi Kwacha');
insert into public.currencies (id, code, name) values (101, '	MYR', '	Malaysian Ringgit');
insert into public.currencies (id, code, name) values (102, '	MVR', '	Rufiyaa');
insert into public.currencies (id, code, name) values (103, '	MRO', '	Ouguiya');
insert into public.currencies (id, code, name) values (104, '	MUR', '	Mauritius Rupee');
insert into public.currencies (id, code, name) values (105, '	XUA', '	ADB Unit of Account');
insert into public.currencies (id, code, name) values (106, '	MXN', '	Mexican Peso');
insert into public.currencies (id, code, name) values (107, '	MXV', '	Mexican Unidad de Inversion');
insert into public.currencies (id, code, name) values (108, '	MDL', '	Moldovan Leu');
insert into public.currencies (id, code, name) values (109, '	MNT', '	Tugrik');
insert into public.currencies (id, code, name) values (110, '	MAD', '	Moroccan Dirham');
insert into public.currencies (id, code, name) values (111, '	MZN', '	Mozambique Metical');
insert into public.currencies (id, code, name) values (112, '	MMK', '	Kyat');
insert into public.currencies (id, code, name) values (113, '	NAD', '	Namibia Dollar');
insert into public.currencies (id, code, name) values (114, '	NPR', '	Nepalese Rupee');
insert into public.currencies (id, code, name) values (115, '	NIO', '	Cordoba Oro');
insert into public.currencies (id, code, name) values (116, '	NGN', '	Naira');
insert into public.currencies (id, code, name) values (117, '	OMR', '	Rial Omani');
insert into public.currencies (id, code, name) values (118, '	PKR', '	Pakistan Rupee');
insert into public.currencies (id, code, name) values (119, '	PAB', '	Balboa');
insert into public.currencies (id, code, name) values (120, '	PGK', '	Kina');
insert into public.currencies (id, code, name) values (121, '	PYG', '	Guarani');
insert into public.currencies (id, code, name) values (122, '	PEN', '	Sol');
insert into public.currencies (id, code, name) values (123, '	PHP', '	Philippine Piso');
insert into public.currencies (id, code, name) values (124, '	PLN', '	Zloty');
insert into public.currencies (id, code, name) values (125, '	QAR', '	Qatari Rial');
insert into public.currencies (id, code, name) values (126, '	RON', '	Romanian Leu');
insert into public.currencies (id, code, name) values (127, '	RWF', '	Rwanda Franc');
insert into public.currencies (id, code, name) values (128, '	SHP', '	Saint Helena Pound');
insert into public.currencies (id, code, name) values (129, '	WST', '	Tala');
insert into public.currencies (id, code, name) values (130, '	STD', '	Dobra');
insert into public.currencies (id, code, name) values (131, '	SAR', '	Saudi Riyal');
insert into public.currencies (id, code, name) values (132, '	RSD', '	Serbian Dinar');
insert into public.currencies (id, code, name) values (133, '	SCR', '	Seychelles Rupee');
insert into public.currencies (id, code, name) values (134, '	SLL', '	Leone');
insert into public.currencies (id, code, name) values (135, '	SGD', '	Singapore Dollar');
insert into public.currencies (id, code, name) values (136, '	XSU', '	Sucre');
insert into public.currencies (id, code, name) values (137, '	SBD', '	Solomon Islands Dollar');
insert into public.currencies (id, code, name) values (138, '	SOS', '	Somali Shilling');
insert into public.currencies (id, code, name) values (139, '	SSP', '	South Sudanese Pound');
insert into public.currencies (id, code, name) values (140, '	LKR', '	Sri Lanka Rupee');
insert into public.currencies (id, code, name) values (141, '	SDG', '	Sudanese Pound');
insert into public.currencies (id, code, name) values (142, '	SRD', '	Surinam Dollar');
insert into public.currencies (id, code, name) values (143, '	SZL', '	Lilangeni');
insert into public.currencies (id, code, name) values (144, '	SEK', '	Swedish Krona');
insert into public.currencies (id, code, name) values (145, '	CHE', '	WIR Euro');
insert into public.currencies (id, code, name) values (146, '	CHW', '	WIR Franc');
insert into public.currencies (id, code, name) values (147, '	SYP', '	Syrian Pound');
insert into public.currencies (id, code, name) values (148, '	TWD', '	New Taiwan Dollar');
insert into public.currencies (id, code, name) values (149, '	TJS', '	Somoni');
insert into public.currencies (id, code, name) values (150, '	TZS', '	Tanzanian Shilling');
insert into public.currencies (id, code, name) values (151, '	THB', '	Baht');
insert into public.currencies (id, code, name) values (152, '	TOP', '	Pa’anga');
insert into public.currencies (id, code, name) values (153, '	TTD', '	Trinidad and Tobago Dollar');
insert into public.currencies (id, code, name) values (154, '	TND', '	Tunisian Dinar');
insert into public.currencies (id, code, name) values (155, '	TRY', '	Turkish Lira');
insert into public.currencies (id, code, name) values (156, '	TMT', '	Turkmenistan New Manat');
insert into public.currencies (id, code, name) values (157, '	UGX', '	Uganda Shilling');
insert into public.currencies (id, code, name) values (158, '	AED', '	UAE Dirham');
insert into public.currencies (id, code, name) values (159, '	UYU', '	Peso Uruguayo');
insert into public.currencies (id, code, name) values (160, '	UYI', '	Uruguay Peso en Unidades Indexadas');
insert into public.currencies (id, code, name) values (161, '	UZS', '	Uzbekistan Sum');
insert into public.currencies (id, code, name) values (162, '	VUV', '	Vatu');
insert into public.currencies (id, code, name) values (163, '	VEF', '	Bolívar');
insert into public.currencies (id, code, name) values (164, '	VND', '	Dong');
insert into public.currencies (id, code, name) values (165, '	YER', '	Yemeni Rial');
insert into public.currencies (id, code, name) values (166, '	ZMW', '	Zambian Kwacha');
insert into public.currencies (id, code, name) values (167, '	ZWL', '	Zimbabwe Dollar');
